# vim: ft=yaml
---
driver:
  name: linode

provisioner:
  name: salt_solo
  formula: cachet
  state_top:
    base:
      "*":
        - cachet

platforms:
  - name: debian_jessie
    driver:
      flavor: 1024
      data_center: Dallas
      kernel: 4.4.0-x86_64-linode56
      image: Debian 8.1

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        cachet.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - cachet
